/*********** Dummy User Data for whatever *************/
const DummyData = {};


DummyData.milestones = {
  1: JSON.parse('{"id":1,"user_id":77,"template_id":null,"category":"Children","subcategory":"Raising children","completed":0,"name":"Raise a happy and healthy child","inspirational_image_url":null,"deadline": "2021-06-30 03:06:46","measure_data":"{\\"type\\": \\"freeform\\"}","start_measure":"Real bad","end_measure":"Sorta okay","vision":"sdfdsfdsfdsf","purpose":"sdfsdfsdfdfsdfsdf","obstacles":"","notes":"","permissions":"[]","created_at":"2021 - 06 - 30T03: 06: 46.000000Z","updated_at":"2021 - 07 - 02T16: 36: 28.000000Z","deleted_at":null}'),
  46: {
    id: 46,
    date_created: 3423523,
    created_by: 77,
    last_seen: 4235436,
    notes: "",
    permissions: null,
    owner_id: 77,
    is_private: false,
    template_milestone_id: null,
    category: "Other",
    subcategory: "Provider Specific",
    milestone_name: "YoungLives Camp",
    inspirational_image_url: "YoungLives Camp",
    deadline: 34987324,
    measure_data: { type: "none" },
    vision: "My vision is...",
    purpose: "My purpose is...",
    obstacles: "My obstacles...",
    complete: true,
    deleted: false
  },
  45: {
    id: 45,
    date_created: 3423523,
    created_by: 77,
    last_seen: 4235436,
    notes: "",
    permissions: null,
    owner_id: 77,
    is_private: false,
    template_milestone_id: null,
    category: "Health",
    subcategory: "Provider Specific",
    milestone_name: "GED",
    inspirational_image_url: "GED",
    deadline: 34987324,
    measure_data: { type: "none" },
    vision: "My vision is...",
    purpose: "My purpose is...",
    obstacles: "My obstacles...",
    complete: true,
    deleted: false
  }
}

DummyData.linksByMilestoneId = {
  46: [{
    name: 'Link for going to google canada',
    url: 'google.ca',
  },
  {
    name: 'Spotify',
    url: 'http://spotify.com',
  }
  ]
}

DummyData.goalsByMilestoneId = {
  /* Camp */
  46: [{
    id: 1042,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Other",
    template_goal_id: null,
    goal_name: "Review Camp Health form (for myself) to learn if my doctor needs to complete any part in addition to providing immunization records",
    repeat_basis: "one-time",
    next_deadline: 1625083200, /* june 30 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 4042,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Other",
    template_goal_id: null,
    goal_name: "Review Camp Health form (for my child/ren) to learn if pediatrician needs to complete any part in addition to providing immunization records",
    repeat_basis: "one-time",
    next_deadline: 1625083200, /* june 30 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 2042,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Other",
    template_goal_id: null,
    goal_name: "If I only need immunization records from my doctor, call doctor's office to arrange pick-up",
    repeat_basis: "one-time",
    next_deadline: 1625688000, /* july 7 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 5042,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Other",
    template_goal_id: null,
    goal_name: "If I only need immunization records for my child/ren from my pediatrician, call pediatrician's office to arrange pick-up",
    repeat_basis: "one-time",
    next_deadline: 1625688000, /* july 7 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }],
  /* Deliver */
  44: [{
    id: 1050,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Children",
    template_goal_id: null,
    goal_name: "Talk with care provider about health foods",
    repeat_basis: "one-time",
    next_deadline: 1620684000, /* May 10 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 2050,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Children",
    template_goal_id: null,
    goal_name: "Ask family or friend to support healthy choices",
    repeat_basis: "one-time",
    next_deadline: 1620788400, /* May 10 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 4050,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Children",
    template_goal_id: null,
    goal_name: "Schedule Self Care",
    repeat_basis: "one-time",
    next_deadline: 1620932400, /* May 13 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 3050,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Children",
    template_goal_id: null,
    goal_name: "Make sure I am up to date on immunizations",
    repeat_basis: "one-time",
    next_deadline: 1621537200, /* May 20 */
    frequency: 1,
    repeat_times: [],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }],
  /* Peace */
  45: [{
    id: 1051,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Health",
    template_goal_id: null,
    goal_name: "Write in Gratitude Journal",
    repeat_basis: "daily",
    next_deadline: 1620345600,
    frequency: 1,
    repeat_times: [20 * 60 * 60],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 2051,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Health",
    template_goal_id: null,
    goal_name: "Pray",
    repeat_basis: "daily",
    next_deadline: 1620352800,
    frequency: 1,
    repeat_times: [12 * 60 * 60, 22 * 60 * 60],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 3051,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Health",
    template_goal_id: null,
    goal_name: "Talk with a friend or family member",
    repeat_basis: "daily",
    next_deadline: 1620421200,
    frequency: 3,
    repeat_times: [17 * 60 * 60],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }, {
    id: 4051,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Health",
    template_goal_id: null,
    goal_name: "Listen to inspiration music",
    repeat_basis: "weekly",
    next_deadline: 1620576000,
    frequency: 1,
    repeat_times: [12 * 60 * 60],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  },
  {
    id: 5051,
    date_created: 12346743,
    last_seen: 123462147,
    notes: "",
    milestone_id: 1,
    owner_id: 90,
    category: "Health",
    template_goal_id: null,
    goal_name: "Find a therapist",
    repeat_basis: "one-time",
    next_deadline: 1622304000,
    frequency: 1,
    repeat_times: [12 * 60 * 60],
    sort_order: 0,
    history: [],
    history_buffer: [],
    streak: 0,
    best_streak: 234,
    total_occurrences: 789,
    total_completions: 678,
    is_private: false,
    active: true,
    deleted: false
  }],
}

export { DummyData }